name: Release es-recorder

on:
  push:
    tags:
    - '*'

jobs:
  publish-docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven # From https://github.com/actions/cache/blob/main/examples.md
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Get release version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - name: Publish Docker image
      env:
        # secrets are defined here : https://github.com/organizations/gisaia/settings/secrets/actions
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        DOCKER_CLOUDSMITH_USERNAME: ${{ secrets.CLOUDSMITH_USER }}
        DOCKER_CLOUDSMITH_PASSWORD: ${{ secrets.CLOUDSMITH_API_KEY }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
      run: bash scripts/ci/publish_docker.sh $RELEASE_VERSION
  publish-npm:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache Maven # From https://github.com/actions/cache/blob/main/examples.md
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Get release version
      id: vars
      run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}
    - uses: actions/setup-node@v2
      with:
        node-version: 16
        registry-url: 'https://registry.npmjs.org'
    - name: Publish NPM client
      env:
        # secrets are defined here : https://github.com/organizations/gisaia/settings/secrets/actions
        DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USER }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}
        NPM_EMAIL: ${{ secrets.NPM_EMAIL }}
        RELEASE_VERSION: ${{ steps.vars.outputs.tag }}
        NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: |
        bash scripts/ci/export_swagger.sh $RELEASE_VERSION
        bash scripts/ci/publish_npm.sh $RELEASE_VERSION